# Generated by Django 5.2 on 2025-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_veiculo_foto_veiculo_preco_alter_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco_diaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
